name: Publication Web

on:
  push:
    branches: [ LABOS ]
    paths:
      - index.html

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    
    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Publication de la page index.html
        run: |
          sudo mkdir -p /var/www/site
          sudo cp index.html /var/www/site/index.html
          sudo chown www-data:www-data /var/www/site/index.html
          sudo systemctl reload nginx
